name: Xtension
description: Extension on default classes to help with normal tasks
version: 0.0.1
author: Leo Letto
homepage:

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: