name: xtension
description: Xtension add some useful extension methods on Dart classes that help you while coding and make easier to have extensions in a single package
version: 0.0.3
homepage: https://github.com/Paradoxu/Xtension
repository: https://github.com/Paradoxu/Xtension
authors:
  - Leo Letto <leandroletto@gmail.com>

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:

dev_dependencies: